### ISSUE TITLE
pubsub error on mac python2.7 

### ISSUE THREAD

**Issue by shangyan0517** [mad-lab/transit#12]
get Error when trying `transit` or `python PATH/src/transit.py`:
`
❯ python2.7 transit.py
Traceback (most recent call last):
  File "transit.py", line 24, in <module>
    import pytransit.__main__
  File "~/transit/src/pytransit/__main__.py", line 27, in <module>
    from wx.lib.pubsub import pub
  File "/usr/local/lib/python2.7/site-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
  File "/usr/local/lib/python2.7/site-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax
`
Solution:
`
pip2.7 uninstall pypubsub
pip2.7 install -Iv https://pypi.python.org/packages/95/5a/1801be1a63af9250e79b8941a37b88e3ca0d660b880b9862fe9016ae6a3a/PyPubSub-3.3.0.zip
`
Thanks jancumps @ https://github.com/xesscorp/xsconnect/issues/1#issue-203356205

**Comment by subsid** [comment]
Thanks. This issue has been fixed in version 2.3.0
