### ISSUE TITLE
Error running ANOVA

### ISSUE THREAD

**Issue by jschreie** [mad-lab/transit#16]
I am attempting to use the ANOVA method on my dataset (in the form of a combined wig file). It took awhile, but I was able to massage my gff file into a prot_table, which I am hoping is in the correct format as the 'combined_wig' function ran smoothly, but only when the first column of my prot_table was a "#" rather than a string of text describing the gene as I see it in the examples of prot_tables provided with TRANSIT. When it is not a "#", the error I receive is:

_Traceback (most recent call last):
  File "/home/jeremy/Desktop/transit/src/transit.py", line 28, in <module>
    pytransit.__main__.run_main()
  File "/home/jeremy/Desktop/transit/src/pytransit/__main__.py", line 42, in run_main
    main(*args, **kwargs)
  File "/home/jeremy/Desktop/transit/src/pytransit/__main__.py", line 105, in main
    methodobj.Run()
  File "/home/jeremy/Desktop/transit/src/pytransit/export/combined_wig.py", line 161, in Run
    hash = transit_tools.get_pos_hash(self.annotation_path)
  File "/home/jeremy/Desktop/transit/src/pytransit/transit_tools.py", line 351, in get_pos_hash
    return tnseq_tools.get_pos_hash_pt(path)
  File "/home/jeremy/Desktop/transit/src/pytransit/tnseq_tools.py", line 1159, in get_pos_hash_pt
    orf = tmp[8]_

When I use the "#" and I am able to combine the wig files, I run into another problem using the ANOVA function with this same prot_table file and the error I receive is this:

_Traceback (most recent call last):
  File "/home/jeremy/Desktop/transit/src/transit.py", line 28, in <module>
    pytransit.__main__.run_main()
  File "/home/jeremy/Desktop/transit/src/pytransit/__main__.py", line 42, in run_main
    main(*args, **kwargs)
  File "/home/jeremy/Desktop/transit/src/pytransit/__main__.py", line 116, in main
    methodobj.Run()
  File "/home/jeremy/Desktop/transit/src/pytransit/analysis/anova.py", line 194, in Run
    genes = tnseq_tools.read_genes(self.annotation_path)
  File "/home/jeremy/Desktop/transit/src/pytransit/tnseq_tools.py", line 68, in read_genes
    "start": int(w[1])-1,
IndexError: list index out of range_

Do you know how I may fix this problem? Is it a bug? And is there going to be support for using a gff file instead of a prot_table for these commands?

Thanks in advance,
Jeremy

**Comment by ioerger** [comment]
Jeremy, I suspect there is a problem with the format of your .prot_table file.
Note that there is a an option in the Transit GUI for automatically converting gff files into the prot_table format.
It is under File->Convert.
Give it a try and let me know if that fixes it.

Thanks,

Tom Ioerger

**Comment by jschreie** [comment]
Thanks Tom!
This fixed the problem, my prot_table was slightly off. Was able to run the ANOVA successfully

**Comment by 4rn01d** [comment]
Hello!

I am trying to run command-line ANOVA on TRANSIT 2.3.4; however, I keep receiving the following error:

Traceback (most recent call last):
  File "C:\Python27\transit-master\src\transit.py", line 28, in <module>
    pytransit.__main__.run_main()
  File "C:\Python27\transit-master\src\pytransit\__main__.py", line 42, in run_main
    main(*args, **kwargs)
  File "C:\Python27\transit-master\src\pytransit\__main__.py", line 116, in main
    methodobj.Run()
  File "C:\Python27\transit-master\src\pytransit\analysis\anova.py", line 190, in Run
    self.read_samples_metadata(self.metadata),
  File "C:\Python27\transit-master\src\pytransit\analysis\anova.py", line 108, in read_samples_metadata
    [condition, wfile] = vals[headIndexes[0]], vals[headIndexes[1]]
IndexError: list index out of range

I was able to obtain a combined wig file through the command-line combined_wig export function of TRANSIT.  I also believe that my prot_table is fine because it is the same prot_table I have successfully used in previous versions of TRANSIT, and it works on this current version via another analysis pipeline (i.e.: Resampling).

Does anyone know about this problem and/or how to fix it?  Or, is it a bug in the ANOVA caused by the recent update from 2.3.3 to 2.3.4?

Thank you for your time!

Arnold

**Comment by subsid** [comment]
Hey Arnold,

Seems like there is an error in the samples metadata file you are using, can you check if its formatted as mentioned in https://transit.readthedocs.io/en/latest/transit_methods.html#id25 ?

**Comment by Midna-lab** [comment]
Was this issue with using ANOVA ever solved?

**Comment by ioerger** [comment]
I think the issue was resolved.
If you have specific questions, please contact me directly at
ioerger@cs.tamu.edu.

Tom
